---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway
  namespace: argocd
  labels:
    app: nginx-gateway
spec:
  destination:
    namespace: nginx-gateway
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: nginx-gateway
    repoURL: oci://ghcr.io/nginx/charts/nginx-gateway-fabric
    targetRevision: 1.6.2
  - repoURL: 'https://github.com/TheLionsRain/homelab-gitops.git'
    path: src/kubernetes/nginx-gateway/manifests
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
