apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-root-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app: core
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: core
  source:
    path: src/kubernetes
    repoURL: 'https://github.com/TheLionsRain/homelab-gitops.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true