---
apiVersion: v1
kind: Secret
metadata:
  name: homelab-gitops
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/TheLionsRain/homelab-gitops.git
  project: core