---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    app: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.17.3
    helm:
      valueFiles:
        - $values/src/kubernetes/cert-manager/values.yml
  - repoURL: 'https://github.com/TheLionsRain/homelab-gitops.git'
    targetRevision: HEAD
    ref: values
  - repoURL: 'https://github.com/TheLionsRain/homelab-gitops.git'
    path: src/kubernetes/cert-manager/manifests
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
